# Generated by Django 3.1.4 on 2021-01-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='checker',
            field=models.IntegerField(default=17),
        ),
    ]
