# Generated by Django 3.1.4 on 2021-01-02 09:58

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='checker',
            field=models.IntegerField(blank=True, default=17),
        ),
        migrations.AlterField(
            model_name='game',
            name='grid',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0), size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(blank=True, choices=[('Started', 'started'), ('Playing', 'playing'), ('Finished', 'finished')], default='Started', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.IntegerField(blank=True, choices=[(1, 'one'), (2, 'two'), (0, 'zero')], default=0),
        ),
    ]
