# Generated by Django 3.1.4 on 2021-01-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210102_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='checker',
        ),
    ]
