# Generated by Django 3.1.5 on 2021-02-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210222_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='col',
            new_name='resp_col',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='row',
            new_name='resp_row',
        ),
    ]
